include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
    - lib/**.config.dart
    - lib/**.gr.dart
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    public_member_api_docs: false
    prefer_single_quotes: true
    sort_constructors_first: true
    sort_pub_dependencies: ignore
    always_specify_types: false
    prefer_const_constructors: true
    lines_longer_than_80_chars: false
