name: rdna_delivery
description: Rdna Delivery Application .
version: 4.24.0+8
publish_to: none

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter_html:
  auto_route: ^5.0.4
  bloc: ^8.0.3
  built_collection: ^5.1.1
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  device_info_plus: ^7.0.1
  dio: ^4.0.6
  dio_http2_adapter: ^2.0.0
  dio_http_formatter: ^2.1.0
  toggle_switch: ^2.0.1


  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  flutter_hooks: ^0.18.3
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.4.0+1
  flutter_secure_storage: ^4.2.1
  flutter_svg: ^1.0.3
  freezed_annotation: ^2.0.1
  gesture_x_detector: ^1.1.0
  get_it: ^7.2.0
  image_picker: ^0.7.2+1
  injectable: ^1.5.3
  internet_connection_checker: ^0.0.1+3
  intl: ^0.18.0
  json_annotation: ^4.4.0
  logger: ^1.1.0
  rxdart: ^0.27.3
  shimmer: ^2.0.0
  
  timeago: ^3.2.2
  uuid: ^3.0.6
  bottom_navy_bar: ^6.0.0
  shared_preferences: ^2.0.15
  carousel_slider: ^4.1.1
  provider: ^6.0.4
  fluttertoast: ^8.1.1
  flutter_slidable: ^2.0.0
  firebase_messaging: ^14.2.1
  firebase_auth: ^4.2.5
  country_picker: ^2.0.16
  firebase_core: ^2.4.1
  change_app_package_name: ^1.1.0
  badges: ^2.0.3
  pin_code_fields: ^7.4.0
  webview_flutter: ^3.0.4
  overlay_support: ^2.1.0
  google_sign_in: ^5.4.4
  flutter_facebook_auth: 
  flutter_local_notifications: ^11.0.0
  url_launcher: ^6.1.10
  

dev_dependencies:
  auto_route_generator: ^5.0.3 
  bloc_test: ^9.0.3
  build_runner: ^2.1.10
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^1.0.4
  flutter_native_splash: ^2.1.6
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3
  http_mock_adapter: ^0.3.2

  injectable_generator: ^1.5.3
  json_serializable: ^6.2.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0
  dotted_border: ^2.0.0+2
  syncfusion_flutter_sliders: ^20.3.47
  http: ^0.13.5
  flutter_rating_bar: ^4.0.1
  timelines: ^0.1.0
  table_calendar: ^3.0.7
  


dependency_overrides:
  analyzer: ^5.6.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/
    

  fonts:
    - family: vazirmatn
      fonts:
        - asset: assets/fonts/vazirmatn/vazirmatn-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/vazirmatn/vazirmatn-Bold.ttf
          weight: 600
        - asset: assets/fonts/vazirmatn/vazirmatn-Medium.ttf
          weight: 500
        - asset: assets/fonts/vazirmatn/vazirmatn-Regular.ttf
          weight: 400

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  main_locale: en
  arb_dir: lib/l10n/arb
  output_dir: lib/l10n/generated

flutter_icons:
  #android: "launcher_icon"
  image_path: "assets/logo/rdna-logo.jpeg"
  min_sdk_android: 21 
  
  web:
    generate: true
    image_path_android: "assets/logo/rdna-logo.jpeg"
    background_color: "#FFCD00"
    theme_color: "#FFCD00"
  ios:
    generate: true
    image_path_ios: "assets/logo/rdna-logo.jpeg"
    background_color: "#FFCD00"
    theme_color: "#FFCD00"

  android:
    generate: true
    image_path: "assets/logo/rdna-logo.jpeg"
    background_color: "#FFCD00"
    theme_color: "#FFCD00"
    
  windows:
    generate: true
    image_path: "assets/logo/rdna-logo.jpeg"
    icon_size: 48 # min:48, max:256, default: 48
  