// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWM-baCrMPNCCgjyLIbB1bbzyxzfNxXeA',
    appId: '1:318952105091:web:a51633625c45e4ec82e7b6',
    messagingSenderId: '318952105091',
    projectId: 'rdna-9416d',
    authDomain: 'rdna-9416d.firebaseapp.com',
    storageBucket: 'rdna-9416d.appspot.com',
    measurementId: 'G-44ERR2QVK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJsgAhIc6qIJ6TGvCu2NkToQZBeO44KKk',
    appId: '1:318952105091:android:7223e6b3fa22a6d982e7b6',
    messagingSenderId: '318952105091',
    projectId: 'rdna-9416d',
    storageBucket: 'rdna-9416d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-3oS0-4NRRkuuFQG5afM3XFT7oemYj5E',
    appId: '1:318952105091:ios:1155f448518209eb82e7b6',
    messagingSenderId: '318952105091',
    projectId: 'rdna-9416d',
    storageBucket: 'rdna-9416d.appspot.com',
    iosClientId: '318952105091-49j0adfk6cfeedj15fbgrha9oibirhaa.apps.googleusercontent.com',
    iosBundleId: 'com.rdnastore.deliveryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-3oS0-4NRRkuuFQG5afM3XFT7oemYj5E',
    appId: '1:318952105091:ios:fbacb855fc24da6f82e7b6',
    messagingSenderId: '318952105091',
    projectId: 'rdna-9416d',
    storageBucket: 'rdna-9416d.appspot.com',
    iosClientId: '318952105091-eq2mht4miobts8v6cjg2popja3aoo6a7.apps.googleusercontent.com',
    iosBundleId: 'com.example.rdnaDelivery',
  );
}
